name: get-git-latest-sha
description: Get SHA value of latest commit in git.
outputs:
  sha:
    description: SHA short value of latest commit in git.
    value: ${{ steps.output-sha.outputs.sha }}
runs:
  using: composite
  steps:
    - name: Install reviewdog if it is not installed
      run: |
        if !(type "reviewdog" > /dev/null 2>&1); then
          REVIEWDOG_VERSION="0.14.1"
          FILE_NAME="reviewdog_${REVIEWDOG_VERSION}_Linux_x86_64.tar.gz"
          wget -q https://github.com/reviewdog/reviewdog/releases/download/v${REVIEWDOG_VERSION}/${FILE_NAME}
          tar -zxf "${FILE_NAME}"
          rm -rf "${FILE_NAME}"
          chmod +x ./reviewdog
          sudo mv reviewdog /usr/local/bin
        fi
        reviewdog -version
      shell: bash
