name: CI
run-name: CI ${{ matrix.image }}
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: ghcr.io/giganticminecraft/seichi_minecraft_server_debug_base_1_12_2
            build_context: ./docker-images/mcservers/debug/seichi-servers/base-images/1_12_2
            image_ver: 1.0.0
          - image: ghcr.io/giganticminecraft/seichi_minecraft_server_debug_seichi_1
            build_context: ./docker-images/mcservers/debug/seichi-servers/individual-images/deb-s1
            image_ver: 1.0.0
          - image: ghcr.io/giganticminecraft/seichi_minecraft_server_debug_seichi_2
            build_context: ./docker-images/mcservers/debug/seichi-servers/individual-images/deb-s2
            image_ver: 1.0.0
    steps:
      - uses: actions/checkout@v4
      - run: echo ${{ matrix.image }}
