name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn init -y
      - run: yarn add http-server
      - run: mkdir src && touch src/index.html
      - run: yarn http-server src
