name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: output
        id: sha
        uses: ./.github/actions/get-git-latest-sha
      - name: Run a one-line script
        run: echo ${{ steps.sha.outputs.sha }}
