name: CI
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: echo docker-compose.yml
        run: curl -sSL https://raw.githubusercontent.com/bitnami/bitnami-docker-redmine/master/docker-compose.yml > docker-compose.yml
      - name: Run redmine
        run: docker-compose up -d
      - run: curl "http://localhost:80/issues.json" | jq .
