name: test
on: push
jobs:
  build-image:
    name: Build Docker image, and Publish on main branch
    runs-on: ubuntu-latest
    steps:
      - run: |
          docker run -d -p 8080:8080 --rm ghcr.io/lucky3028/mecab-server
          docker container ls
          curl --verbose -X POST -H 'Content-Type: application/json' -d "{"texts": ["8月3日"]}" http://localhost:8080/parse
      - if: always
        run: |
          docker logs $(docker ps -a | grep mecab | awk '{print $1}')
